### ISSUE TITLE
Incompatible license for AGPL

### ISSUE THREAD

**Issue by chakravala** [eschnett/DifferentialForms.jl#1]
You are copying some of my code from [Grassmann.jl](https://github.com/chakravala/Grassmann.jl) and [DirectSum.jl](https://github.com/chakravala/DirectSum.jl) and using an incompatible license.

**Comment by eschnett** [comment]
I am not copying code from these two repositories. Please provide details.

**Comment by chakravala** [comment]
You stated yourself that you copied some things from me, and it is evident that your code is a derivative of mine. It is an interesting modification, one definitely worthwhile to have a look at. Nevertheless, its design is a derivative modification of the code I published. e.g.
```julia
@computed struct Form{D,R,T}
    elts::SVector{binomial(Val(D), Val(R)),T}
end
```
using `ComputedFieldTypes` wasn't even possible before I fixed up the package, I was the first person to use this construction for the exterior algebra code generation, then you derived it from me.
```julia
function bits2uint(bits::SVector{D,Bool}) where {D}
    ubits = Unsigned(0)
    for d in 1:D
        ubits += Unsigned(bits[d]) << (d - 1)
    end
    return ubits::Unsigned
end
```
you also derived various other pieces of code from my repositories using principles I developed

it's a nice derivative work based on algorithms, data structures, and techniques you learned from my repositories, so it would be classy for you to honor the license i made this learning material available under

**Comment by eschnett** [comment]
The two code fragments you show are generic. The first is a fixed-sized array in a struct, the second converts between two integer bit representations. There is no connection to differential forms or generic algebra. Your claim that I am copying your code has no substance.
